//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutec.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class advances
    {
        public int id_advance { get; set; }
        public short advance_type { get; set; }
        public string advance_detail { get; set; }
        public byte[] time { get; set; }
        public int id_service { get; set; }
    
        public virtual services services { get; set; }
    }
}
