//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutec.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class brands
    {
        public int id_brand { get; set; }
        public string commercial_name { get; set; }
        public string nit { get; set; }
        public string nrc { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public bool is_active { get; set; }
    }
}
