//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solutec.Models
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public services()
        {
            this.advances = new ObservableCollection<advances>();
        }
    
        public int id_service { get; set; }
        public int id_customer { get; set; }
        public Nullable<int> id_brand { get; set; }
        public string unique_reference { get; set; }
        public string commercial_invoice { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public string model { get; set; }
        public bool is_warranty { get; set; }
        public int technical_operator { get; set; }
        public System.DateTime in_date { get; set; }
        public Nullable<System.DateTime> out_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<advances> advances { get; set; }
        public virtual customers customers { get; set; }
        public virtual users users { get; set; }
    }
}
